/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import clases.Succionador;
import java.awt.Color;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ethan
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    
    private ArrayList<Succionador> Succionadores;
            
    public Inicio() {
        initComponents();
        Succionadores=new ArrayList<Succionador>();
        
        Succionadores.add(new Succionador("Benja","1211111-1",LocalDate.of(2020,10,30),100,99));
        Succionadores.add(new Succionador("Cristobal","12321312-1",LocalDate.of(2021,2,21),70,9999));
        Succionadores.add(new Succionador("Vicho negro","234232-1",LocalDate.of(2022,7,16),20,9999999));
        Actualizar();
    }
    
    
    private void Actualizar(){
        
        DefaultTableModel DT=new DefaultTableModel();
        DT.addColumn("nombre");
        DT.addColumn("rut");
        DT.addColumn("Fecha_Inicio");
        DT.addColumn("cap_suc");
        DT.addColumn("penes_chupados");
        

        Object[] fila=new Object[5];
        for (Succionador suc:Succionadores) { 
            fila[0]=suc.getNombre();
            fila[1]=suc.getRut();
            fila[2]=suc.getFecha_Inicio();
            fila[3]=suc.getCap_suc();
            fila[4]=suc.getPenes_chupados();
            DT.addRow(fila);
        }

        jTable1.setModel(DT);
        jTable1.setAutoCreateRowSorter(false);
        
        
        //Estupidez:
        ArrayList<Color> colores= new ArrayList<Color>();
        colores.add(Color.red);
        colores.add(Color.blue);
        colores.add(Color.green);
        colores.add(Color.black);
        colores.add(Color.white);
        colores.add(Color.CYAN);
        colores.add(Color.ORANGE);
        colores.add(Color.yellow);
        colores.add(Color.MAGENTA);
        jLabel1.setForeground(colores.get(new Random().nextInt(colores.size())));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ActualizarBoton = new javax.swing.JButton();
        AgregarBoton = new javax.swing.JButton();
        EditarAmante = new javax.swing.JButton();
        EliminarAmante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido a Chupamelapichula");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        ActualizarBoton.setText("Actualizar");
        ActualizarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualizarBotonMouseClicked(evt);
            }
        });

        AgregarBoton.setText("Agregar un amante de la pichula");
        AgregarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarBotonMouseClicked(evt);
            }
        });

        EditarAmante.setText("Editar un amante de la pichula");
        EditarAmante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarAmanteMouseClicked(evt);
            }
        });

        EliminarAmante.setText("Eliminar un amante de la pichula");
        EliminarAmante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarAmanteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ActualizarBoton)
                                .addGap(30, 30, 30)
                                .addComponent(AgregarBoton)
                                .addGap(18, 18, 18)
                                .addComponent(EditarAmante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(EliminarAmante))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ActualizarBoton)
                    .addComponent(AgregarBoton)
                    .addComponent(EditarAmante)
                    .addComponent(EliminarAmante))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActualizarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarBotonMouseClicked
        // TODO add your handling code here:
        Actualizar();
    }//GEN-LAST:event_ActualizarBotonMouseClicked

    private void AgregarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarBotonMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuccionadorVista(Succionadores).setVisible(true);
            }
        });
    }//GEN-LAST:event_AgregarBotonMouseClicked

    private void EditarAmanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarAmanteMouseClicked
        // TODO add your handling code here:
        
        System.out.println(jTable1.getSelectedRow());
        if(jTable1.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "[Error al editar]\nSeleccione en la tabla el registro a editar", "Sin selección", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuccionadorVista(Succionadores,Succionadores.get(jTable1.getSelectedRow())).setVisible(true);
            }
        });
    }//GEN-LAST:event_EditarAmanteMouseClicked

    private void EliminarAmanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarAmanteMouseClicked
        // TODO add your handling code here:
         System.out.println(jTable1.getSelectedRow());
        if(jTable1.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "[Error al eliminar]\nSeleccione en la tabla el registro a eliminar", "Sin selección", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Succionadores.remove(jTable1.getSelectedRow());
        JOptionPane.showMessageDialog(null, "[Eliminador Válido]", "Eliminado correctamente", JOptionPane.DEFAULT_OPTION);
        Actualizar();
    }//GEN-LAST:event_EliminarAmanteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarBoton;
    private javax.swing.JButton AgregarBoton;
    private javax.swing.JButton EditarAmante;
    private javax.swing.JButton EliminarAmante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
